// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_ticaret_proje.Models;

#nullable disable

namespace e_ticaret_proje.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251008174221_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("e_ticaret_proje.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdı = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdı = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdı = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdı = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdı = "Giyim",
                            Url = "giyim"
                        });
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 10000.0,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 1"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 20000.0,
                            KategoriId = 2,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 2"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 30000.0,
                            KategoriId = 3,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 3"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 40000.0,
                            KategoriId = 4,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 4"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            KategoriId = 4,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 5"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 60000.0,
                            KategoriId = 1,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 6"
                        });
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Urun", b =>
                {
                    b.HasOne("e_ticaret_proje.Models.Kategori", "Kategori")
                        .WithMany("uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Kategori", b =>
                {
                    b.Navigation("uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
