// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_ticaret_proje.Models;

#nullable disable

namespace e_ticaret_proje.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251009150130_AddSliderContext")]
    partial class AddSliderContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("e_ticaret_proje.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Kategori 1",
                            Url = "Kategori-1"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Kategori 2",
                            Url = "Kategori-2"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Kategori 3",
                            Url = "Kategori-3"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Kategori 4",
                            Url = "Kategori-4"
                        },
                        new
                        {
                            Id = 10,
                            KategoriAdi = "Kategori 5",
                            Url = "Kategori-5"
                        },
                        new
                        {
                            Id = 11,
                            KategoriAdi = "Kategori 6",
                            Url = "Kategori-6"
                        });
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sliderlar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Slider 1",
                            Aktif = true,
                            Baslik = "Slider 1 Başlık",
                            Resim = "slider-1.jpeg",
                            Sira = 0
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Slider 2",
                            Aktif = true,
                            Baslik = "Slider 2 Başlık",
                            Resim = "slider-2.jpeg",
                            Sira = 1
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Slider 3",
                            Aktif = true,
                            Baslik = "Slider 3 Başlık",
                            Resim = "slider-3.jpeg",
                            Sira = 2
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Slider 4",
                            Aktif = true,
                            Baslik = "Slider 4 Başlık",
                            Resim = "slider-1.jpeg",
                            Sira = 3
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Slider 5",
                            Aktif = true,
                            Baslik = "Slider 5 Başlık",
                            Resim = "slider-2.jpeg",
                            Sira = 4
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Slider 6",
                            Aktif = true,
                            Baslik = "Slider 6 Başlık",
                            Resim = "slider-3.jpeg",
                            Sira = 5
                        });
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 10000.0,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 1"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 20000.0,
                            KategoriId = 2,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 2"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 30000.0,
                            KategoriId = 3,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 3"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 40000.0,
                            KategoriId = 4,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 4"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            KategoriId = 4,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 5"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 60000.0,
                            KategoriId = 1,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 6"
                        });
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Urun", b =>
                {
                    b.HasOne("e_ticaret_proje.Models.Kategori", "Kategori")
                        .WithMany("uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("e_ticaret_proje.Models.Kategori", b =>
                {
                    b.Navigation("uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
