// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_ticaret_proje.Models;

#nullable disable

namespace e_ticaret_proje.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("e_ticaret_proje.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 10000.0,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 1"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 20000.0,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 2"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 30000.0,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 3"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = false,
                            Anasayfa = true,
                            Fiyat = 40000.0,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 4"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 5"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "lorem falan filanfalan",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 60000.0,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
